" Config Plugs
source ~/.vim/plugs.vim
source ~/.vim/config/leaderf.vim
source ~/.vim/config/nerdtree.vim
source ~/.vim/config/ctags.vim
source ~/.vim/config/tagbar.vim
source ~/.vim/config/airline.vim
source ~/.vim/config/rainbow.vim
source ~/.vim/config/init.vim
